export * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
export * from 'vscode-oniguruma'
export * from './configuration'
export * from './providers'
export * from './register'
export { default as VsCodeDarkTheme } from './vs-dark-plus-theme'
